---
  # Pass -e "user=myid" to playbook
  - hosts: all
    gather_facts: false
    become: yes
    vars_prompt:
     - name: "userpw"    
       prompt: "Enter password to update on all servers "
       private: yes    
       encrypt: "md5_crypt"
       confirm: yes    
       salt_size: 7
    tasks:
      - name: Change user password
        user: name={{ user }} update_password=always password={{ userpw }}
      - name: Copy authorized_keys for user
        # Make sure to copy the user's key to /etc/ansible/users_public_keys/myid_id_rsa.pub, 'myid' = user
        authorized_key: user={{ user }} key="{{ lookup('file', '/etc/ansible/users_public_keys/' + user + '_id_rsa.pub') }}"
